/**
 * Products Catalog Data - AUTO PEÇAS E MOTO PEÇAS
 * Catálogo completo de produtos para a loja
 */

const catalogProducts = [
    // ==================== FREIOS ====================
    {
        id: 'prod_001',
        name: 'Kit Pastilha de Freio Dianteira Cerâmica',
        sku: 'FRE-001',
        price: 149.90,
        salePrice: 119.90,
        image: 'https://via.placeholder.com/400x400/FF6B00/FFFFFF?text=Pastilha+Freio',
        category: 'Freios',
        brand: 'Fras-le',
        vehicleType: 'Carro',
        stock: 45,
        fastShipping: true,
        inStock: true,
        featured: true,
        rating: 4.8,
        reviews: 156,
        description: 'Kit completo de pastilhas de freio dianteiras em material cerâmico de alta performance.',
        specs: { 'Material': 'Cerâmica', 'Posição': 'Dianteira' },
        compatibility: ['Gol', 'Palio', 'Uno', 'Corsa']
    },
    {
        id: 'prod_006',
        name: 'Disco de Freio Ventilado 280mm',
        sku: 'FRE-006',
        price: 189.90,
        salePrice: 159.90,
        image: 'https://via.placeholder.com/400x400/FF6B00/FFFFFF?text=Disco+Freio',
        category: 'Freios',
        brand: 'Fremax',
        vehicleType: 'Carro',
        stock: 32,
        fastShipping: true,
        inStock: true,
        featured: true,
        rating: 4.9,
        reviews: 89,
        description: 'Disco de freio ventilado de alta durabilidade.',
        specs: { 'Diâmetro': '280mm', 'Espessura': '24mm' },
        compatibility: ['Civic', 'Corolla', 'Focus']
    },
    {
        id: 'prod_007',
        name: 'Cilindro Mestre de Freio',
        sku: 'FRE-007',
        price: 249.90,
        salePrice: null,
        image: 'https://via.placeholder.com/400x400/FF6B00/FFFFFF?text=Cilindro+Freio',
        category: 'Freios',
        brand: 'Varga',
        vehicleType: 'Carro',
        stock: 18,
        fastShipping: false,
        inStock: true,
        featured: false,
        rating: 4.5,
        reviews: 45,
        description: 'Cilindro mestre de freio original.',
        specs: { 'Diâmetro': '23.81mm', 'Roscas': '2' },
        compatibility: ['Gol G5', 'Voyage']
    },

    // ==================== MOTOR ====================
    {
        id: 'prod_002',
        name: 'Filtro de Óleo Mann W950/26',
        sku: 'MOT-002',
        price: 45.90,
        salePrice: 34.90,
        image: 'https://via.placeholder.com/400x400/1a1a1a/FFFFFF?text=Filtro+Oleo',
        category: 'Motor',
        brand: 'Mann Filter',
        vehicleType: 'Universal',
        stock: 150,
        fastShipping: true,
        inStock: true,
        featured: true,
        rating: 5.0,
        reviews: 256,
        description: 'Filtro de óleo original Mann Filter com alta eficiência.',
        specs: { 'Tipo': 'Cartucho', 'Rosca': 'M20 x 1.5' },
        compatibility: ['Universal']
    },
    {
        id: 'prod_005',
        name: 'Kit Correia Dentada Gates com Tensor',
        sku: 'MOT-005',
        price: 289.90,
        salePrice: 249.90,
        image: 'https://via.placeholder.com/400x400/27ae60/FFFFFF?text=Correia',
        category: 'Motor',
        brand: 'Gates',
        vehicleType: 'Carro',
        stock: 28,
        fastShipping: true,
        inStock: true,
        featured: false,
        rating: 4.7,
        reviews: 103,
        description: 'Kit completo de correia dentada com tensor.',
        specs: { 'Dentes': '123', 'Largura': '25mm' },
        compatibility: ['Gol 1.0', 'Palio 1.0']
    },
    {
        id: 'prod_010',
        name: 'Bomba d\'Água Automotiva',
        sku: 'MOT-010',
        price: 179.90,
        salePrice: null,
        image: 'https://via.placeholder.com/400x400/0066CC/FFFFFF?text=Bomba+Agua',
        category: 'Motor',
        brand: 'Nakata',
        vehicleType: 'Carro',
        stock: 42,
        fastShipping: false,
        inStock: true,
        featured: false,
        rating: 4.4,
        reviews: 67,
        description: 'Bomba d\'água de alta performance.',
        specs: { 'Tipo': 'Centrífuga', 'Material': 'Alumínio' },
        compatibility: ['Gol', 'Palio', 'Uno']
    },

    // ==================== SUSPENSÃO ====================
    {
        id: 'prod_003',
        name: 'Amortecedor Traseiro Cofap Honda CG',
        sku: 'SUS-003',
        price: 189.90,
        salePrice: 159.90,
        image: 'https://via.placeholder.com/400x400/FF0000/FFFFFF?text=Amortecedor',
        category: 'Suspensão',
        brand: 'Cofap',
        vehicleType: 'Moto',
        stock: 35,
        fastShipping: true,
        inStock: true,
        featured: true,
        rating: 4.6,
        reviews: 92,
        description: 'Amortecedor traseiro original para motos Honda CG.',
        specs: { 'Posição': 'Traseiro', 'Comprimento': '340mm' },
        compatibility: ['CG 125', 'CG 150', 'CG Titan']
    },
    {
        id: 'prod_011',
        name: 'Kit Amortecedor Dianteiro Nakata',
        sku: 'SUS-011',
        price: 459.90,
        salePrice: 399.90,
        image: 'https://via.placeholder.com/400x400/FF6B00/FFFFFF?text=Amortecedor+Par',
        category: 'Suspensão',
        brand: 'Nakata',
        vehicleType: 'Carro',
        stock: 24,
        fastShipping: true,
        inStock: true,
        featured: true,
        rating: 4.8,
        reviews: 78,
        description: 'Par de amortecedores dianteiros de alta qualidade.',
        specs: { 'Posição': 'Dianteira', 'Tipo': 'Telescópico' },
        compatibility: ['Gol', 'Palio', 'Uno']
    },
    {
        id: 'prod_012',
        name: 'Barra Estabilizadora Traseira',
        sku: 'SUS-012',
        price: 129.90,
        salePrice: null,
        image: 'https://via.placeholder.com/400x400/666666/FFFFFF?text=Barra+Estabilizadora',
        category: 'Suspensão',
        brand: 'TRW',
        vehicleType: 'Carro',
        stock: 19,
        fastShipping: false,
        inStock: true,
        featured: false,
        rating: 4.3,
        reviews: 34,
        description: 'Barra estabilizadora traseira para melhor dirigibilidade.',
        specs: { 'Posição': 'Traseira', 'Material': 'Aço' },
        compatibility: ['Gol G5', 'Fox']
    },

    // ==================== ELÉTRICA ====================
    {
        id: 'prod_004',
        name: 'Bateria Moura 60Ah Selada',
        sku: 'ELE-004',
        price: 459.90,
        salePrice: 399.90,
        image: 'https://via.placeholder.com/400x400/0066FF/FFFFFF?text=Bateria',
        category: 'Elétrica',
        brand: 'Moura',
        vehicleType: 'Carro',
        stock: 56,
        fastShipping: false,
        inStock: true,
        featured: true,
        rating: 4.9,
        reviews: 201,
        description: 'Bateria automotiva Moura 60Ah selada livre de manutenção.',
        specs: { 'Amperagem': '60Ah', 'Voltagem': '12V', 'CCA': '500A' },
        compatibility: ['Gol', 'Fox', 'Polo', 'Voyage']
    },
    {
        id: 'prod_013',
        name: 'Vela de Ignição NGK Iridium',
        sku: 'ELE-013',
        price: 49.90,
        salePrice: 39.90,
        image: 'https://via.placeholder.com/400x400/FF6B00/FFFFFF?text=Vela+Ignicao',
        category: 'Elétrica',
        brand: 'NGK',
        vehicleType: 'Carro',
        stock: 120,
        fastShipping: true,
        inStock: true,
        featured: true,
        rating: 5.0,
        reviews: 345,
        description: 'Vela de ignição premium com eletrodo de irídio.',
        specs: { 'Eletrodo': 'Irídio', 'Abertura': '0.8mm' },
        compatibility: ['Universal']
    },
    {
        id: 'prod_014',
        name: 'Alternador Bosch 90A',
        sku: 'ELE-014',
        price: 689.90,
        salePrice: 599.90,
        image: 'https://via.placeholder.com/400x400/1a1a1a/FFFFFF?text=Alternador',
        category: 'Elétrica',
        brand: 'Bosch',
        vehicleType: 'Carro',
        stock: 15,
        fastShipping: false,
        inStock: true,
        featured: false,
        rating: 4.7,
        reviews: 56,
        description: 'Alternador original Bosch 90 amperes.',
        specs: { 'Amperagem': '90A', 'Voltagem': '12V' },
        compatibility: ['Gol', 'Voyage', 'Saveiro']
    },

    // ==================== FILTROS ====================
    {
        id: 'prod_015',
        name: 'Filtro de Ar Esportivo K&N',
        sku: 'FIL-015',
        price: 229.90,
        salePrice: 199.90,
        image: 'https://via.placeholder.com/400x400/FF0000/FFFFFF?text=Filtro+Ar',
        category: 'Filtros',
        brand: 'K&N',
        vehicleType: 'Carro',
        stock: 38,
        fastShipping: true,
        inStock: true,
        featured: true,
        rating: 4.9,
        reviews: 112,
        description: 'Filtro de ar esportivo lavável de alto fluxo.',
        specs: { 'Tipo': 'Esportivo', 'Lavável': 'Sim' },
        compatibility: ['Gol', 'Palio', 'Uno']
    },
    {
        id: 'prod_016',
        name: 'Filtro de Combustível Tecfil',
        sku: 'FIL-016',
        price: 38.90,
        salePrice: 29.90,
        image: 'https://via.placeholder.com/400x400/27ae60/FFFFFF?text=Filtro+Combustivel',
        category: 'Filtros',
        brand: 'Tecfil',
        vehicleType: 'Carro',
        stock: 95,
        fastShipping: true,
        inStock: true,
        featured: false,
        rating: 4.6,
        reviews: 78,
        description: 'Filtro de combustível de alta eficiência.',
        specs: { 'Tipo': 'Cartucho', 'Material': 'Papel' },
        compatibility: ['Diversos modelos']
    },
    {
        id: 'prod_017',
        name: 'Filtro de Cabine Carvão Ativado',
        sku: 'FIL-017',
        price: 65.90,
        salePrice: null,
        image: 'https://via.placeholder.com/400x400/0066CC/FFFFFF?text=Filtro+Cabine',
        category: 'Filtros',
        brand: 'Mann Filter',
        vehicleType: 'Carro',
        stock: 67,
        fastShipping: true,
        inStock: true,
        featured: false,
        rating: 4.5,
        reviews: 45,
        description: 'Filtro de cabine com carvão ativado anti-pólen.',
        specs: { 'Tipo': 'Carvão Ativado', 'Anti-pólen': 'Sim' },
        compatibility: ['Gol', 'Fox', 'Polo']
    },

    // ==================== ILUMINAÇÃO ====================
    {
        id: 'prod_018',
        name: 'Lâmpada LED H4 8000 Lumens',
        sku: 'ILU-018',
        price: 149.90,
        salePrice: 119.90,
        image: 'https://via.placeholder.com/400x400/FFD700/000000?text=Lampada+LED',
        category: 'Iluminação',
        brand: 'Philips',
        vehicleType: 'Carro',
        stock: 88,
        fastShipping: true,
        inStock: true,
        featured: true,
        rating: 4.8,
        reviews: 167,
        description: 'Lâmpada LED de alta potência 8000 lumens.',
        specs: { 'Tipo': 'LED', 'Lumens': '8000lm', 'Cor': '6500K' },
        compatibility: ['Universal H4']
    },
    {
        id: 'prod_019',
        name: 'Farol Auxiliar de Milha LED',
        sku: 'ILU-019',
        price: 189.90,
        salePrice: 159.90,
        image: 'https://via.placeholder.com/400x400/FF6B00/FFFFFF?text=Farol+Milha',
        category: 'Iluminação',
        brand: 'Hella',
        vehicleType: 'Carro',
        stock: 44,
        fastShipping: true,
        inStock: true,
        featured: false,
        rating: 4.7,
        reviews: 92,
        description: 'Par de faróis de milha LED de alta intensidade.',
        specs: { 'Tipo': 'LED', 'Potência': '20W', 'Cor': '6000K' },
        compatibility: ['Universal']
    },
    {
        id: 'prod_020',
        name: 'Lanterna Traseira LED Fumê',
        sku: 'ILU-020',
        price: 229.90,
        salePrice: null,
        image: 'https://via.placeholder.com/400x400/666666/FFFFFF?text=Lanterna',
        category: 'Iluminação',
        brand: 'Arteb',
        vehicleType: 'Carro',
        stock: 22,
        fastShipping: false,
        inStock: true,
        featured: false,
        rating: 4.6,
        reviews: 34,
        description: 'Lanterna traseira LED com lente fumê.',
        specs: { 'Tipo': 'LED', 'Cor': 'Fumê', 'Posição': 'Traseira' },
        compatibility: ['Gol G5', 'G6', 'G7']
    }
];

// Mapa de ícones para categorias
const categoryIcons = {
    'Motor': '🔧',
    'Freios': '🛑',
    'Suspensão': '🔩',
    'Elétrica': '⚡',
    'Filtros': '🌀',
    'Iluminação': '💡',
    'Acessórios': '🎯'
};

// Extrair categorias únicas com formato correto {id, name, icon}
const categoryNames = [...new Set(catalogProducts.map(p => p.category))].sort();
const categories = categoryNames.map(name => ({
    id: name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''),
    name: name,
    icon: categoryIcons[name] || '📦'
}));

// Extrair marcas únicas
const brands = [...new Set(catalogProducts.map(p => p.brand))].sort();

// Export
window.catalogProducts = catalogProducts;
window.categories = categories;
window.brands = brands;

